### ISSUE TITLE
Use prometheus-community/ansible instead of cloudalchemy/ansible-prometheus after deprecation

### ISSUE THREAD

**Issue by PACordonnier** [TOSIT-IO/tdp-observability#27]
[Cloud Alchemy Prometheus Role](https://github.com/cloudalchemy/ansible-prometheus) has recently been deprecated in favor of [Prometheus Community Ansible role](https://github.com/prometheus-community/ansible).

**Comment by rpignolet** [comment]
It would be nice if we could use the community role, but from what I've seen we're going to have integration problems. For example in the community role, the restart of the service is done via an Ansible `notify` whereas in TDP we have a tool (`tdp-lib`) which drives this restart.
