### ISSUE TITLE
Prometheus systemd service start when running install and config action

### ISSUE THREAD

**Issue by rpignolet** [TOSIT-IO/tdp-observability#28]
This issue may be solved by #27.

When running `prometheus_server_install.yml` or `prometheus_server_config.yml`, prometheus systemd service is started as we see in the Ansible log when running `prometheus_server_config.yml`:
```
RUNNING HANDLER [cloudalchemy.prometheus : reload prometheus] ************************************
changed: [prometheus-01]
```

The cause is we using an external Prometheus role which follows Ansible standard rules to notify service to reload them when configuration files are modified. In TDP we do not follow these rules and use `tdp-lib` to launch specific operation in order.
We should not use external role to install Prometheus in order to have a good integration in TDP.

**Comment by giem-git** [comment]
This issue has been fixed by #52
