### ISSUE TITLE
Use LTS version for Prometheus by default

### ISSUE THREAD

**Issue by rpignolet** [TOSIT-IO/tdp-observability#29]
Prometheus have LTS version: https://prometheus.io/docs/introduction/release-cycle/.

I think we should use, by default a LTS version of Prometheus which is 2.37 currently. We use 2.38:
https://github.com/TOSIT-IO/tdp-observability/blob/a527cd52a5eb10f4daa04ee240d0229b5cb8daf0/tdp_vars_defaults/prometheus/prometheus.yml#L7

**Comment by PACordonnier** [comment]
Agreed 👍
