### ISSUE TITLE
Prometheus installs fails on Rocky8

### ISSUE THREAD

**Issue by PACordonnier** [TOSIT-IO/tdp-observability#39]
This error shows up when installing prometheus on Rocky 8 (I use vagrant box `generic/rocky8` with getting-started)

```
TASK [cloudalchemy.prometheus : Install SELinux dependencies] ********************************************************************************************************************************************************************************
failed: [master-01] (item=libselinux-python) => changed=false 
  ansible_loop_var: item
  attempts: 5
  failures:
  - 'libselinux-python All matches were filtered out by modular filtering for argument: libselinux-python'
  item: libselinux-python
  msg: Failed to install some of the specified packages
  rc: 1
  results: []
```

Related to PR  https://github.com/cloudalchemy/ansible-prometheus/pull/366 and issue https://github.com/cloudalchemy/ansible-prometheus/issues/389 which won't be fixed because role is deprecated

Should be fixed by #27

**Comment by rpignolet** [comment]
This task use `prometheus_selinux_packages` variable to know packages to install. This variable is empty by default https://github.com/TOSIT-IO/tdp-observability/blob/167630e9da875fed3407a99aed82a88921a63fff/tdp_vars_defaults/prometheus/prometheus.yml#L29.

Do you override this variable ?

**Comment by PACordonnier** [comment]
I was not on the latest commit [167630e](https://github.com/TOSIT-IO/tdp-observability/commit/167630e9da875fed3407a99aed82a88921a63fff) which solves the issue

I was even more in the wrong since it tried to install RHEL7 packages instead of RHEL8, I just assumed that the role did not manage RHEL8 correctly, thanks @rpignolet
