### ISSUE TITLE
dependency for prometheus not installed 

### ISSUE THREAD

**Issue by GuillaumeHold** [TOSIT-IO/tdp-observability#46]
## Observation

In the `cloudalchemy.prometheus` role and `tdp-observability` at `2dc1432cde6e00f796f017384176abceb54ad504`, the package `policycoreutils-python` have difficulties to be installed.

The play `Prometheus Server Install` fail with : 
```
fatal: [master-01]: FAILED! => changed=false 
  msg: Failed to import the required Python library (policycoreutils-python) on master-01's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter
```
## Workarround

The package can be installed manually with : `sudo yum install policycoreutils-python`

**Comment by kpgtek** [comment]
```cloudalchemy.prometheus``` role is not used now, and I can not have this error.

On Rocky8 system, we can find the following packages, before deploying Prometheus:
```
policycoreutils-python-utils
policycoreutils
python3-policycoreutils
```

**Comment by giem-git** [comment]
This issue is now irrelevant. We do not use `cloudalchemy.prometheus` anymore

**Comment by giem-git** [comment]
Close issue
