### ISSUE TITLE
loki/promtail : collect all tdp logs

### ISSUE THREAD

**Issue by giem-git** [TOSIT-IO/tdp-observability#50]
tdp logs are not collected. 
Logs that should be collected :
- `xxxx_log_dir/*.log`  for all log_dirs defined in tdp-collection's tdp-cluster.yml
- `xxx_log_dir/*.log` defined in various files from tdp-collection-extras

Additionaly, maybe other logs should be collected :
- ldap
- kerberos 
- postgres
- system logs
- observability logs
- etc ?

**Comment by gonzaloetjo** [comment]
In case you want to discuss these topics, today and every friday we have the developers-call at 14:00 Paris time https://meet.goto.com/tdp

**Comment by giem-git** [comment]
> In case you want to discuss these topics, today and every friday we have the developers-call at 14:00 Paris time https://meet.goto.com/tdp

Thanks, I will attend
