### ISSUE TITLE
Grafana admin_password is not taken into account

### ISSUE THREAD

**Issue by Nuttymoon** [TOSIT-IO/tdp-observability#6]
The `admin_password` variable is not taken into account: the admin user/password remains `admin/admin` instead of:

https://github.com/alliage-io/tdp-monitoring/blob/ebe689aa85ddfe9ecbfc52b5866e710b4b807be5/tdp_vars_defaults/grafana/grafana.yml#L19-L21

**Comment by kpgtek** [comment]
After checking, I think this issue has been fixed.
