### ISSUE TITLE
Add github workflows to tdp_observability

### ISSUE THREAD

**Issue by giem-git** [TOSIT-IO/tdp-observability#62]
- Add to tdp_observability the same github workflows as tdp_collection : 
  - Check license headers
  - Check conventional commits
  - Ansible-lint
- Adapt code to pass these checks

**Comment by rpignolet** [comment]
Maybe you should split into 2 PR, one for licence headers and conventional commits and another for ansible-lint. This will allow us to merge quickly the first PR and have the licence and conventional commits checks.
